### ISSUE TITLE
Query Regarding Oracle-Maps

### ISSUE THREAD

**Issue by KenaHemnani** [saimwani/multiON#4]

**Comment by KenaHemnani** [comment]
Hii, thank you for such great work !! 
Can you tell me for which scenes you provide Oracle-Maps Matterport3D or Gibson? In the Oracle Maps do you include all the object of the scene?

**Comment by shivanshpatel35** [comment]
We provide oracle maps for Matterport3D scenes. These are stored in `map300.pickle` file. It contains occupancy maps (each location is either occupied, not occupied or outside the scene) for all the scenes. It does not contain scene specific object information explicitly.

**Comment by KenaHemnani** [comment]
Thank you for the quick response @shivanshpatel35 . But in the https://youtu.be/yqTlHNIcgnY video explanation it is mentioned that Oracle-Map agents are provided with complete information of the agents containing occupancy and object information. Also, reading the paper I understood the same. May be I understood incorrectly.  Thank you once again.

**Comment by shivanshpatel35** [comment]
Object information refers to the target objects (inserted colored cylinders) and it is episode-specific. This information is included in the oracle map. For instance, an episode of 3-ON with OracleMap agent will have an oracle map with three objects. These target objects have nothing to do with the remaining scene objects.

**Comment by KenaHemnani** [comment]
Okay, Thanks for clearing the doubt . Thank you very much for your quick response.

**Comment by nnsriram97** [comment]
Hey, I tried to load the oracle maps (`map300.pickle`) and visualize it but found the maps to contain very little information. For example, executing `np.count_nonzero(mapCache[some_map_key])` shows around only 1000 pixels contain some information although the map resolution appears to be 300x300. Here's an example of map key and number of pixels with information for few sequences.

```
data/scene_datasets/mp3d/b8cTxDM8gDG/b8cTxDM8gDG.glb 686
data/scene_datasets/mp3d/17DRP5sb8fy/17DRP5sb8fy.glb 252
data/scene_datasets/mp3d/TbHJrupSAjP/TbHJrupSAjP.glb 360
data/scene_datasets/mp3d/Vt2qJdWjCF2/Vt2qJdWjCF2.glb 3096
data/scene_datasets/mp3d/gTV8FGcVJC9/gTV8FGcVJC9.glb 697
data/scene_datasets/mp3d/QUCTc6BB5sX/QUCTc6BB5sX.glb 2166
data/scene_datasets/mp3d/VVfe2KiqLaN/VVfe2KiqLaN.glb 437
```

Am I missing something here?
