### ISSUE TITLE
Why the FALSE_FOUND_PENALTY is set as False in examples

### ISSUE THREAD

**Issue by ZhuFengdaaa** [saimwani/multiON#8]
As shown in [habitat_baselines/config/multinav/ppo_multinav.yaml#L22](https://github.com/saimwani/multiON/blob/main/habitat_baselines/config/multinav/ppo_multinav.yaml#L22), the FALSE_FOUND_PENALTY is set as `False`. Will the agent learns to yield "found" every step?

**Comment by saimwani** [comment]
Hi,
A single false FOUND action terminates the episode. As such, there is an implicit penalty for calling a false FOUND and therefore the agent does not learn to call FOUND at every step. During our experiments, we did not see much benefit from adding an explicit negative reward for a false FOUND action.

**Comment by ZhuFengdaaa** [comment]
Thank you for your help!
