### ISSUE TITLE
How the multiON dataset is generated? 

### ISSUE THREAD

**Issue by ZhuFengdaaa** [saimwani/multiON#9]
How the multiON dataset is generated, including the algorithms of generating (x,y) distributions of the starting positions and the target positions. 

------------------------------------update----------------------------------------
I have found the `generate_pointnav_episode()` function in `pointnav_generator.py`. However, this function can only sample the target position rather than the object target class. Could you please share a complete script of data generation for point goal and object goal respectively? 

Thanks.

**Comment by saimwani** [comment]
Please refer to the [Habitat Lab](https://github.com/facebookresearch/habitat-lab) repository for details about PointNav and ObjectNav dataset generation. For MultiON, the agent starting position and goal locations are randomly sampled as pairs of points on the same floor within each environment between which there exists a navigable path. The geodesic distance from the agent starting position to the first goal and between successive goals is constrained to be between 2m and 20m. 

Specifically, we choose a random position on the floor as the starting point. Following this, we choose a random location on the same floor as a candidate for the first object goal. If this location is not navigable from the previous point or if its distance from the previous point does not lie between 2m and 20m, it is discarded and another candidate location is chosen. The same process is followed to generate the consequent object goals.

**Comment by nnsriram97** [comment]
Hey, is code for generating the dataset available? And can you point me to the code where cylinders are inserted in the scene for sampled locations? Thanks!

**Comment by saimwani** [comment]
Hi, code for generating dataset is not public right now but it should be easy to write your own script. We might release ours with the next update. Cylinders are inserted into the environment [here](https://github.com/saimwani/multiON/blob/2ba4d25678dff9a990dc5e98ad81fd8c0a1bf15c/habitat/core/env.py#L255). Hope that helps.
